name:                stack-sample
version:             0.1.0.0
github:              "githubuser/stack-sample"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/stack-sample#readme>

language: GHC2021

dependencies:
- base >= 4.7 && < 5
- Cabal
- Cabal-syntax
- QuickCheck
- adjunctions
- array
- attoparsec
- base
- bifunctors
- binary
- bitvec
- bytestring
- comonad
- containers
- contravariant
- deepseq
- directory
- distributive
- exceptions
- extra
- fgl
- filepath
- free
- ghc-bignum
- ghc-boot-th
- ghc-prim
- hashable
- heaps
- indexed-traversable
- indexed-traversable-instances
- integer-gmp
- integer-logarithms
- kan-extensions
- lens
- linear-base
- list-t
- massiv
- megaparsec
- mono-traversable
- mtl
- mutable-containers
- mwc-random
- parallel
- parsec
- parser-combinators
- pretty
- primitive
- process
- profunctors
- psqueues
- random
- reflection
- regex-tdfa
- safe-exceptions
- scientific
- semialign
- semigroupoids
- split
- stm
- strict
- strict-lens
- tagged
- template-haskell
- text
- tf-random
- these
- these-lens
- time
- transformers
- trifecta
- unboxing-vector
- unix
- unordered-containers
- utility-ht
- vector
- vector-algorithms
- vector-stream
- vector-th-unbox
- xhtml

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

# - -threaded
# - -rtsopts
# - -with-rtsopts=-N

# library:
#   source-dirs: src

executables:
  a-exe:
    source-dirs: "a"
    main:                Main.hs

  b-exe:
    source-dirs: "b"
    main:                Main.hs

  c-exe:
    source-dirs: "c"
    main:                Main.hs

  d-exe:
    source-dirs: "d"
    main:                Main.hs

  e-exe:
    source-dirs: "e"
    main:                Main.hs

  f-exe:
    source-dirs: "f"
    main:                Main.hs

  g-exe:
    source-dirs: "g"
    main:                Main.hs

# tests:
#   stack-sample-test:
#     main:                Spec.hs
#     source-dirs:         test

